### PR TITLE
feat(faker): unique data generation

### PR DESCRIPTION
**Pull request by System-Glitch**
Refer to issue #76 

- Added a `unique` tag to generate unique data.
    - Call `ResetUnique()` after generating a dataset to forget all already generated values
- Added tests for the new feature
- Added unique support for `Lorem` generator as a proposal for the single fake data functions. My implementation is redundant. **Any feedback would be appreciated before implementing it to the other single fake data functions.**
    - Call `SetGenerateUniqueValues(true)` to enable unique data generation on single fake data functions
    - Call `SetGenerateUniqueValues(false)` to disable it
    - Call `ResetUnique()` to forget all already generated values

This change shouldn't break backwards compatibility.

TODO:

- [x] Update documentation
- [x] Implement unique handling in all single fake data functions

### CODE REVIEW

**Comment by bxcodec** [comment]
Any updates on this PR @System-Glitch

**Comment by System-Glitch** [comment]
@bxcodec Well I was waiting for feedback on the single fake data functions before continuing.

**Comment by System-Glitch** [comment]
```go    
if generateUniqueValues {
	v, err := generateUnique(PARAGRAPH, func() interface{} {
		return i.paragraph()
	})
	if err != nil {
		panic(err)
	}
	return v.(string)
}
```
This part is redundant. It has to be there for every single fake data function. Maybe you have an idea to make it better?

I though about another function to factor this.
```go
func singleUnique(dataType string, fn func() interface{}) (interface{}, error) {
	v, err := generateUnique(dataType, fn)
	if err != nil {
		panic(err)
	}
	return v
}
```
That would shorten a single fake data function like this.
```go    
func Word() string {
	i := Lorem{}
	if generateUniqueValues {
		return singleUnique(WORD, func() interface{} {
			return i.paragraph()
		}).(string)
	}

	return i.word()
}
```

**Comment by System-Glitch** [comment]
PR is ready to be merged.

**Comment by bxcodec** [comment]
Thanks for the PR @System-Glitch  👍

**Pull request merged**
